---

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: ubuntu-15.10
  - name: ubuntu-16.04
  - name: debian-8.1
  - name: debian-8.2
  - name: debian-8.3
  - name: debian-8.4
  - name: debian-8.5
  - name: debian-8.6
  - name: debian-7.11
  - name: debian-7.10
  - name: debian-7.9
  - name: debian-7.8

suites:
  - name: default-12
    run_list:
      - recipe[devopsdance-nginx::_tests]
    provisioner:
      require_chef_omnibus: 12
  - name: default-13
    run_list:
      - recipe[devopsdance-nginx::_tests]
    provisioner:
      require_chef_omnibus: 13

